---
title: "Lab 03"
author: "Yating Zeng"
date: "9/7/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1. Read in the data

```{r 1.Read the data}
if (!file.exists("met_all.gz")){
  download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", 
                method="libcurl", timeout = 60)
}

library(R.utils)
met <- data.table::fread("met_all.gz")
```

## Step 2. Check the dimensions, headers, footers. How many columns, rows are there?

```{r 2.Check the dimensions, headers, footers}
dim(met)
head(met)
tail(met)
```

## Step 3. Take a look at the variables.

```{r 3.Take a look at the variables}
str(met)
summary(met[,8:12])
```

## Step 4. Take a closer look at the key variables.

```{r 4.Take a closer look at the key variables}
table(met$year)
```

```{r}
table(met$day)
```

```{r}
table(met$hour)
```

```{r}
summary(met$temp)
```
```{r}
summary(met$elev)
```
```{r}
summary(met$wind.sp)
```
OR by alternative codes
```{r}
met[, summary(elev)]
summary(met$temp)
summary(met$wind.sp)
```

Replace elevations with 9999 as NA.

```{r}
met[met$elev==9999.0] <- NA
summary(met$elev)
```

The weather station with the highest elevation is at `r max(met$elev, na.rm=TRUE)` meters

```{r checking the missing value}
mean(is.na(met$temp))
```